import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header/Header";
import Navbar from "../components/Navbar/Navbar";
import About from "../components/About/About";
import Experience from "../components/Experience/Experience";
import Projects from "../components/Projects/Projects";
import Achievements from "../components/Achievements/Achievements";
import Skills from "../components/Skills/Skills";
import Footer from "../components/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Ansh Choudhary",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Navbar />
        <About />
        <Experience />
        <Projects />
        <Achievements />
        <Skills />
        <Footer />
        {children}</body>
    </html>
  );
}
